# AI設定。
ai:
  prompt: "以下の対話型AIとのやり取りによって私が学んだ内容を、プログラミングの学習記録として個人用ブログに上げようと思います。箇条書きを使いながら日本語で1000字以内でまとめてください。タイトルもください。返事はいりません。："
  model: "gemini-2.5-flash"
  thoughts_level: -1 # 0 for thoghtless, -1 for dynamic thoughts (think thoughts level itself), 1-24576 to set thoughts limit

paths:
  input_dir: "sample"
  output_dir: "outputs"

other:
  debug: "true"
